/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package tutorial;


import java.util.HashMap;
import java.util.Map;


public class Constants {

  public static final int INT32CONSTANT = 9853;

  public static final Map<String,String> MAPCONSTANT = new HashMap<String,String>(); 
  static {
    MAPCONSTANT.put("hello", "world");
    MAPCONSTANT.put("goodnight", "moon");
  }

}